### ISSUE TITLE
jquery menus

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/fade#28]
The following code works to open and close a single menu but not when there are multiple of the same menus on the screen.

```javascript
$(document).ready(function() {
  //appends an "active" class to .popup and .popup-content when the "Open" button is clicked
  $(".open").on("click", function(){
    $(".popup-overlay, .popup-content").addClass("active");
  });

//removes the "active" class to .popup and .popup-content when the "Close" button is clicked
  $(".close, .popup-overlay").on("click", function(){
    $(".popup-overlay, .popup-content").removeClass("active");
  });
});
```

**Comment by Hallm13** [comment]
This code works on the portfolio site to add a class to only the element that is clicked (or in this case touched on mobile). It will not close the menu again unless you touch another element.

```javascript
$(document).ready(function() {
 $('.feature-overlay').on('touchstart', function(){
 $('.active').removeClass('active');
 this.classList.toggle('active');
 });
});
```

**Comment by Hallm13** [comment]
try this
https://codereview.stackexchange.com/questions/116098/dropdown-function
https://plnkr.co/edit/3mdULmI2QEcWmpDCzXQb?p=preview

javascript
```javascript
(function(){
    var dropDownClass = 'dropdown-content';
    var showClass = 'show';
    var dropDowns = document.getElementsByClassName('dropdown');

    var open = function(e){
        var openDropDown = e.target.nextElementSibling;
        var dropdowns = document.getElementsByClassName(dropDownClass);
        
        openDropDown.classList.toggle(showClass);

        var closeDropDown = function(event) {
            if (event.target === e.target) {
                return;
            }
            if (openDropDown.classList.contains(showClass)) {
                openDropDown.classList.remove(showClass);
            }
            window.removeEventListener('click', closeDropDown);
        };
        window.addEventListener('click', closeDropDown);
    }

    for(var i = 0; i < dropDowns.length; i++){
        dropDowns[i].children[0].addEventListener('click', open);
    }
}());
```

html
```html
<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="style.css">
    
  </head>

  <body>
    <div class="dropdown">
<button>Dropdown</button>
  <div class="dropdown-content">
    <a href="#home">Home</a>
    <a href="#about">About</a>
    <a href="#contact">Contact</a>
  </div>
</div>
<div class="dropdown">
<button>Dropdown</button>
  <div class="dropdown-content">
    <a href="#home">Home</a>
    <a href="#about">About</a>
    <a href="#contact">Contact</a>
  </div>
</div>
<script src="script.js"></script>
  </body>

</html>
```

css
```css
body{
  font-family: Arial;
}

button{
  cursor: pointer;
  border: 1px solid #aaa;
  padding: 7px;
  padding-left: 10px;
  padding-right: 10px;
  box-sizing: border-box;
  width: 100%;
}

.dropdown{
  position: relative;
  float: left;
  margin: 5px;
  width: 120px;
}

.dropbtn:hover, .dropbtn:focus {
    background-color: #3e8e41;
}

.dropdown-content {
    max-height: 0;
    overflow: hidden;
    position: absolute;
    background-color: #f9f9f9;
    transition: max-height 400ms ease;
    box-shadow: 1px 1px 10px rgba(0,0,0,0.2);
    width: 100%;
}

.dropdown-content a {
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown a:hover {background-color: #f1f1f1}
.show {
  max-height: 170px;
}
```
